.github/workflows/_security-checks.yaml
.github/workflows/on-pr.yaml

Adds Trivy and npm audit checks.

Add security check workflow

---

docs/about/changelog.md
docs/how-to/install.md

Now that we have the semver tags being published, adding notes to the install how-to and the changelog.

Add changelog and install notes about image tags

---

.github/workflows/_security-checks.yaml
.github/workflows/_static-checks.yaml
.github/workflows/on-pr.yaml

Pin actions to SHA and set permissions on reusable workflows.

Update GitHub Actions security

---

.markdownlint.json

While we should avoid bare URLs, the fix for this rule (surrounding the URL with <>) breaks rendering, since Docusaurus currently runs all files through the MDX engine and a < is interpreted as a JSX tag.
This PR also sorts the .markdownlint.json config alphabetically by the alias names instead of by the rule ID.

Disable MD034 / no-bare-urls

---

docs/about/changelog.md
docs/about/faq.md
docs/how-to/install.md
docs/how-to/use-with-aider.mdx
docs/index.md
docs/partials/_aider-providers.mdx

Merge when stacklok/codegate#543 is released.

Add docs for Aider support

---

docs/how-to/use-with-aider.mdx
docs/how-to/use-with-continue.mdx
docs/how-to/use-with-copilot.mdx
docs/quickstart-copilot.mdx

A few minor touch-ups:
- The Copilot integration now supports the codegate-version prompt, replacing the previous verification step.
- Refresh the example responses about malicious packages with current language.

Minor docs updates for sample prompts

---

docs/quickstart-continue.mdx
docs/quickstart-copilot.mdx

Reflect the updates to the codegate-demonstration repo

Update demo file references

---

.lintstagedrc
docs/how-to/use-with-aider.mdx
docs/how-to/use-with-continue.mdx
docs/how-to/use-with-copilot.mdx
docs/quickstart-continue.mdx
docs/quickstart-copilot.mdx

On the next release, `codegate-version` will change to `codegate version`. Merge this once release goes out

Update codegate-version command

---

docs/quickstart-continue.mdx
docs/quickstart-copilot.mdx

The prior command is `cd codegate-demonstration`; the next command should be to open `code` in the current directory.

Open code in codegate-demonstration folder

---

docs/partials/_aider-providers.mdx

Per https://github.com/stacklok/codegate/issues/586#issuecomment-2595218413

Update Aider command line for Ollama

---

.github/dependabot.yaml

Dependabot's getting a little noisy especially with the dev deps. This groups all the lint/formatting tools and backs off to weekly scans.
Also pins react to major version, which shouldn't be an issue for a while, but could have bit us recently with v19.

Update Dependabot config

---

STYLE-GUIDE.md
docs/about/changelog.md
docs/how-to/install.md
docs/how-to/use-with-aider.mdx
docs/index.md
docs/partials/_aider-providers.mdx

Aider is written lowercase unless it starts a setence (like this one :smile:). Fixing docs to reflect that.

Fix aider naming style

---

docs/index.md
docs/integrations/copilot.mdx

Correcting the certificate instructions for Linux - VS Code on Linux apparently uses the user's nssdb, not the system certs. I validated the updated instructions on Ubuntu and Fedora.
Ref stacklok/codegate#695
This fixes the instructions in the docs; there's also a pending UI update to address this in the dashboard instructions.

Fix cert instructions

---

docs/partials/_cline-providers.mdx

See the original page here, specifically the box for the Anthropic provider configuration: https://docs.codegate.ai/integrations/cline?provider=anthropic
In the screenshot which shows the configuration needed for Codegate, the URL uses http whereas the instructions use https. Since port 8989 appears to be serving http traffic, it seems like http is the correct one.

Fix protocol for Cline Anthropic integration

---

docs/features/workspaces.mdx
docs/index.md
docs/integrations/aider.mdx
docs/partials/_aider-providers.mdx
docs/partials/_cline-providers.mdx
package-lock.json

Mostly catching up the workspaces page to new stuff in the UI - the preset prompts and new edit menu.

Minor updates

---

docs/how-to/install.md
docs/integrations/aider.mdx
docs/integrations/cline.mdx
docs/integrations/continue.mdx
docs/integrations/copilot.mdx
docs/integrations/open-interpreter.mdx
docs/quickstart-continue.mdx
docs/quickstart-copilot.mdx

I was annoyed that it was 4 commands to upgrade codegate; this reduces it to 3 commands.  It might be possible to make an upgrade button if we can plumb through the docker socket into the container...

Simplify container restart command

---

docs/integrations/copilot.mdx
docs/quickstart-copilot.mdx

If you have a file open, when running `codegate version`, you get a response based on the file and not the codegate version itself. I've added a note to inform users that they close all files before running the command. Outside of this PR, we may want to decide if this is desired functionality by Copilot or Codegate and if the version should be returned regardless if a file is currently open or not.

fix: adds note for copilot docs

---

docs/integrations/avante.mdx

The support for avante.nvim hasn't shipped in a release yet, so this marks the page as unlisted.
It will still be available at https://docs.codegate.ai/integrations/avante but is hidden from navigation.
Revert this after the next release.

Mark avante integration as unlisted

---

docs/about/changelog.md
docs/index.md
docs/integrations/avante.mdx

Since v0.1.24 is out now, re-listing the avante.nvim integration doc.
Also updated it to follow the same pattern as the other integration docs.

Re-list and update avante.nvim docs

---

.devcontainer/devcontainer.json
README.md
docs/integrations/copilot.mdx
package.json

Adds a Dev Container config for the docs.
Also adds a troubleshooting note for CodeGate + Copilot + Dev Containers that I ran across while working on this.

Add Dev Container

---

docs/about/changelog.md
docs/features/secrets-redaction.md
docs/index.md
docs/quickstart-continue.mdx
docs/quickstart-copilot.mdx
vercel.json

https://github.com/stacklok/codegate/pull/1123 replaced the secrets encryption process with the same UUID-based redaction used for the PII pipeline. This updates the docs to reflect that.

Replace secrets encryption with redaction

---

docs/how-to/configure.md
docs/how-to/install.mdx

New DASHBOARD_BASE_API_URL parameter added in https://github.com/stacklok/codegate/pull/1231, so building a customized image is no longer needed.
Also moved the note about this deployment method lower on the install page to de-emphasize it a bit since it's not our recommended pattern.

Update the method for running CodeGate remotely

---

docs/features/workspaces.mdx
docs/how-to/configure.md
docs/how-to/install.mdx
package-lock.json

Add DB backup/restore instructions

---

docs/about/faq.md
docs/development/index.md
docs/features/workspaces.mdx

Adding some more questions to the FAQ.
Also adds token tracking to the workspaces feature page, and links to the 2 newer developer reference guides.

Add more FAQs

---

docs/how-to/configure.md

A small typo in the environment variable DASHBOARD_API_BASE_URL, where “api” and “base” were switched.
[source code](https://github.com/stacklok/codegate/blob/9b4806efe37ffc0c059bc9993b40ed3cca63c6eb/scripts/entrypoint.sh#L33)

fix(env-var): adjust name for DASHBOARD_API_BASE_URL

---

docs/about/faq.md
docs/how-to/troubleshooting.md
package-lock.json

Adds a troubleshooting guide
Closes #56

Troubleshooting-guide
